기본 저장 타입인 Tensor는 Numpy와 유사한 기능을 제공한다.

https://pytorch.org/docs/stable/generated/torch.tensor.html

https://pytorch.org/docs/stable/tensors.html


In [1]:
import numpy as np
import torch

In [2]:
# 리스트로부터 텐서를 만들수 있다.

t1 = torch.tensor([[1,2],[3,4]])

In [3]:
type(t1)

torch.Tensor

In [4]:
t1.dtype #타입 확인

torch.int64

In [5]:
# 타입 지정 가능

t2 = torch.tensor([[1,2],[3,4]], dtype=torch.float64)

In [6]:
t2.dtype

torch.float64

pytorch는 변수나 모델에 대한 저장 device 지정이 필요함

https://tutorials.pytorch.kr/recipes/recipes/save_load_across_devices.html


In [8]:
t1.device   #gpu 런타임으로 실행하여 저장한 변수이나, 기본적으로 텐서는 cpu에 저장됨

device(type='cpu')

In [9]:
device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')   # 사용할 디바이스 지정을 위해서 추가, gpu 사용가능 시에는 gpu 사용, 아니면 cpu 사용

if device.type == 'cuda':
    print(torch.cuda.get_device_name(0))

Tesla K80


In [10]:
device

device(type='cuda')

In [11]:
t3 = torch.tensor([[1,2],[3,4]], device = 'cuda')  #device 지정

In [ ]:
t3.device

device(type='cuda', index=0)

In [13]:
t4 = torch.tensor([[1,2],[3,4]], device = 'cuda:0')  # 디바이스가 여러개일때는 뒤에 번호를 추가하여 구분 가능함

In [14]:
t4.device

device(type='cuda', index=0)

gpu에 저장된 변수를 numpy로 변환 시에 오류가 발생 함

Numpy로 변환 시 gpu device의 tensor는 cpu로 이동 후 변환

In [15]:
t4.numpy()  # gpu device로 설정된 텐서를 numpy로 변환시 에러가 발생

TypeError: ignored

In [16]:
t4.to('cpu').numpy()  # cpu 변환 후 numpy로 변환

array([[1, 2],
       [3, 4]])

tensor의 인덱싱 및 연산은 numpy와 거의 동일

In [ ]:
t4[:,1]

tensor([2, 4], device='cuda:0')

In [ ]:
t3 + t4

tensor([[2, 4],
        [6, 8]], device='cuda:0')

디바이스가 다른 경우에 연산 오류 발생함, 동일한 디바이스로 맞춰주어야 함

In [17]:
t1+t4   # t1이 cpu인 경우 gpu의 t4와 연산 안됨, 동일한 device로 맞춰줘야 함

RuntimeError: ignored

In [18]:
t1+t4.to('cpu')

tensor([[2, 4],
        [6, 8]])

데이터 병합 시 torch.cat() 사용

https://pytorch.org/docs/stable/generated/torch.cat.html


In [19]:
t5=torch.tensor([[1,2],[3,4]])
t6=torch.tensor([[10,20,30],[30,40,50]])

In [20]:
t5

tensor([[1, 2],
        [3, 4]])

In [21]:
t6

tensor([[10, 20, 30],
        [30, 40, 50]])

In [22]:
t6.size()

torch.Size([2, 3])

In [23]:
t6.t()

tensor([[10, 30],
        [20, 40],
        [30, 50]])

In [24]:
torch.cat([t5,t6], dim=1)

tensor([[ 1,  2, 10, 20, 30],
        [ 3,  4, 30, 40, 50]])

In [25]:
t7=torch.cat([t5,t6.t()], dim=0)

In [ ]:
t7

tensor([[ 1,  2],
        [ 3,  4],
        [10, 30],
        [20, 40],
        [30, 50]])

배열의 reshape은 view() 사용

https://pytorch.org/docs/stable/generated/torch.Tensor.view.html

In [26]:
t7.view(1,-1)  #-1 입력한 dim은 자동으로 추론하여 계산되어 변경

tensor([[ 1,  2,  3,  4, 10, 30, 20, 40, 30, 50]])

In [29]:
t7.view(2,5)

tensor([[ 1,  2,  3,  4, 10],
        [30, 20, 40, 30, 50]])